### ISSUE TITLE
Limiting obtaining the logins to the ones listed in permissions param.

### ISSUE THREAD

**Issue by brunoais** [web-ext-experiments/logins#10]
I think the origin for the login permissions should be limited to the urls specified in the `"permissions"` parameter in the JSON object in the `manifest.json` file.

Of course, as it is already specified, all logins stored by the addon are always available to that same addon.

What are your opinions?

**Comment by aswan** [comment]
I'm not sure I understand, are you proposing that extensions don't get access to login information that they create themselves without adding an additional site permission?

**Comment by brunoais** [comment]
No. From my post above:

> all logins stored by the addon are always available to that same addon.

As for the other ones, I think that by giving permissions to an addon to work with a page, that addon should have access to all logins related to that page.

**Comment by aswan** [comment]
> I think that by giving permissions to an addon to work with a page, that addon should have access to all logins related to that page.

But this is how it already works.  See the second to last paragraph at https://github.com/web-ext-experiments/logins/blob/master/api.md#permissions

**Comment by brunoais** [comment]
My fail then. Sorry.
