### ISSUE TITLE
Rename formSubmitURL to formActionOrigin

### ISSUE THREAD

**Issue by mnoorenberghe** [web-ext-experiments/logins#12]
Along the lines of #8, can we fix more of pwmgr's poor naming? (see also [bug 1148205](https://bugzilla.mozilla.org/show_bug.cgi?id=1148205)). This isn't a URL, it's an origin and so should be labelled as such. I propose:
`formActionOrigin` which is what I'm trying to use in pwmgr code from now on: https://dxr.mozilla.org/mozilla-central/rev/f9362554866b327700c7f9b18050d7b7eb3d2b23/toolkit/components/passwordmgr/nsLoginManager.js#385

**Comment by bobsilverberg** [comment]
Sounds good. I'm going to make this change in my copy of the API code which will end up in m-c.

**Comment by martinthomson** [comment]
+1, I was going to say the same thing.  It's an origin.

**Comment by bobsilverberg** [comment]
This has been dealt with in the code I wrote to bring this API into Firefox. That effort is on hold, but the current state of the code can be seen at https://reviewboard.mozilla.org/r/130860/#review135888.
