### ISSUE TITLE
Rename `realm` property name

### ISSUE THREAD

**Issue by mnoorenberghe** [web-ext-experiments/logins#13]
Changing `httpRealm` to `realm` makes this API more confusing. The "http" prefix was referring to HTTP authentication. Without that prefix is makes me think it's just the login's realm and not related to HTTP auth.

We will also likely add cross-origin realm support in the future allowing a login for e.g. login.mozilla.**org** to be used on foo.mozilla.**com** and that probably won't use the `httpRealm` field and so the generic "realm" name will be even more confusing then. See [bug 1120684](https://bugzilla.mozilla.org/show_bug.cgi?id=1120684).

I suggest we stick with `httpRealm` or clarify with `httpAuthRealm` instead.

**Comment by bobsilverberg** [comment]
@aswan Which do you prefer, sticking with `httpRealm` as it is in nsILoginInfo, or switching it to `httpAuthRealm`?

**Comment by aswan** [comment]
I don't know enough here to have a meaningful opinion, I would go with @mnoorenberghe 's suggestion

**Comment by martinthomson** [comment]
`httpRealm` sounds right.  This appears to be exclusively HTTP, and it avoids issues of confusion.

**Comment by bobsilverberg** [comment]
This has been dealt with in the code I wrote to bring this API into Firefox. That effort is on hold, but the current state of the code can be seen at https://reviewboard.mozilla.org/r/130860/#review135888.
