### ISSUE TITLE
Password manager access with filtering argument

### ISSUE THREAD

**Issue by sarahavilov** [web-ext-experiments/logins#15]
It is useful to have a method that opens the password manager window with a string/url being inserted in the search-box field. Like `browser.logins.openManager({filter: url})`

```JS
openDialog({
  url: 'chrome://passwordmgr/content/passwordManager.xul',
  features: 'chrome=yes,resizable=yes,toolbar=yes,centerscreen=yes,modal=no,dependent=no,dialog=no',
  args: {filterString: 'string goes here'}
});
```

**Comment by bobsilverberg** [comment]
@sarahavilov Please see my comment on issue #14. This should be opened as a bug on Bugzilla.
