### ISSUE TITLE
Doesn't work anymore on Firefox Developers Edition

### ISSUE THREAD

**Issue by jsperf-account** [web-ext-experiments/logins#16]
Since Firefox Developers Edition 54.0b14 (32bit / Win7) this extension can't be loaded anymore temporary by using "about:debugging". This seems to be a general issue, extension type 256 isn't recognized as a valid type.

**Comment by andymckay** [comment]
You've opened this issue on multiple repos, only one is needed. Please refer to the comments in web-ext-experiments/about#14
