### ISSUE TITLE
Consider rename of hostname to origin

### ISSUE THREAD

**Issue by jonathanKingston** [web-ext-experiments/logins#8]
As the API accepts hostname but permits a protocol and port etc should it really be called origin?

**Comment by aswan** [comment]
Heh, looks like the docs are out of date, the implementation already works that way!
And in the process of creating a PR to fix this I goofed and pushed the change directly to master: https://github.com/web-ext-experiments/logins/commit/94bca23e9384d360fa8a02421913cf89c39090e6
If anybody objects I'll revert it and create a proper PR but this makes the docs consistent with the implementation...

**Comment by jonathanKingston** [comment]
Sorry I noticed the inconsistency after filing the bug and didn't update.
Thanks!
